/* eslint-disable no-undef */

const sidebars = {
  Vim: [
    {
      type: 'autogenerated',
      dirName: 'Tech/Vim'
    }
  ],
  Vue: [
    {
      type: 'autogenerated',
      dirName: 'Tech/Vue'
    }
  ],
  React: [
    {
      type: 'autogenerated',
      dirName: 'Tech/React'
    }
  ],
  TDD:[
    {
      type: 'autogenerated',
      dirName: 'Tech/TDD'
    }
  ] 
};

module.exports = sidebars;
